name: Docker Image CI

on:
  push:
    branches: [ "ros-devel-insoles" , "ros" ]
  pull_request:
    branches: [ "ros" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -f ros.Dockerfile -t rosopensimrt/opensim-rt:$(date +%s)
